name: Notion PR Sync

on:

pull_request:

types: [opened, synchronize, reopened, closed]

jobs:

update_notion_page:

runs-on: ubuntu-latest

env:

NOTION_TOKEN: $ secrets.NOTION_TOKEN

NOTION_PAGE_ID: $ secrets.NOTION_PAGE_ID

PR_TITLE: $ github.event.pull_request.title

PR_URL: $ github.event.pull_request.html_url

PR_STATE: $ github.event.pull_request.state  # open | closed

PR_MERGED: $ github.event.pull_request.merged  # true|false (stringy)

REPO: $ github.repository

SHA: $ github.sha

steps:

- name: Post PR update to Notion
    
    run: |
    
    # Build a friendly status line
    
    if [ "${PR_STATE}" = "closed" ] && [ "${PR_MERGED}" = "true" ]; then
    
    STATUS="Merged"
    
    elif [ "${PR_STATE}" = "closed" ]; then
    
    STATUS="Closed"
    
    else
    
    STATUS="Open"
    
    fi
    
    BODY=$(cat <<EOF
    
    {
    
    "children": [
    
    {
    
    "paragraph": {
    
    "rich_text": [
    
    { "type":"text", "text": { "content": "Repo: ${REPO}  •  ${STATUS}" } }
    
    ]
    
    }
    
    },
    
    {
    
    "paragraph": {
    
    "rich_text": [
    
    { "type":"text", "text": { "content": "PR: ${PR_TITLE}  →  " } },
    
    { "type":"text", "text": { "content": "${PR_URL}", "link": { "url": "${PR_URL}" } } }
    
    ]
    
    }
    
    },
    
    {
    
    "paragraph": {
    
    "rich_text": [
    
    { "type":"text", "text": { "content": "SHA: ${SHA}" } }
    
    ]
    
    }
    
    },
    
    { "divider": {} }
    
    ]
    
    }
    
    EOF
    
    )
    
    curl -sS https://api.notion.com/v1/blocks/${NOTION_PAGE_ID}/children \
    
    -H "Authorization: Bearer ${NOTION_TOKEN}" \
    
    -H "Notion-Version: 2022-06-28" \
    
    -H "Content-Type: application/json" \
    
    -X PATCH \
    
    --data "${BODY}" \
    jq -e '.object' >/dev/null
