name: Notion Sync

on:

pull_request:

types: [opened, synchronize, closed]

jobs:

push_to_notion:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v4
- name: Update Notion
    
    env:
    
    NOTION_TOKEN: $ secrets.NOTION_TOKEN
    
    NOTION_PAGE_ID: $ secrets.NOTION_PAGE_ID
    
    run: |
    
    PR_TITLE="$ github.event.pull_request.title "
    
    PR_URL="$ github.event.pull_request.html_url "
    
    curl -s https://api.notion.com/v1/pages/$NOTION_PAGE_ID \
    
    -H "Authorization: Bearer $NOTION_TOKEN" \
    
    -H "Notion-Version: 2022-06-28" \
    
    -H "Content-Type: application/json" \
    
    -X PATCH \
    
    --data "{"properties":{"Name":{"title":[{"text":{"content":"$PR_TITLE"}}]}},"children":[{"paragraph":{"rich_text":[{"type":"text","text":{"content":"$PR_URL"}}]}}]}"
